import dayjs from 'dayjs';
import dayOfYear from 'dayjs/plugin/dayOfYear';

dayjs.extend(dayOfYear);

// 365 Daily Questions (English)
export const questions = [
  "What's the most memorable moment of your day?",
  "If you could describe your mood in one word, what would it be?",
  "What made you smile today?",
  "What was the hardest moment today?",
  "Rate your day from 1 to 10. Why?",
  "Who are you grateful for today?",
  "What would you like to say to yourself?",
  "What did you learn today?",
  "When did you feel good about a choice you made?",
  "How much did you grow compared to yesterday?",
  "Are you satisfied with today?",
  "What color represents you today?",
  "What made you angry today?",
  "When did you feel most like yourself?",
  "What was your most peaceful moment today?",
  "Do you have any regrets about today?",
  "What did you focus on today?",
  "What small success did you have today?",
  "When did you feel most rested today?",
  "When did your heart feel warm today?",
  "How did the weather affect you today?",
  "Who did you talk to the most today?",
  "What made you laugh the hardest?",
  "Who did you say 'thank you' to today?",
  "If your day were a song, what would it be?",
  "When were you laziest today?",
  "Did you praise yourself today?",
  "What thought bothered you today?",
  "If you could capture today in one photo, what would it be?",
  "Who did you inspire today?",
  "What scent describes your day?",
  "When were you most absorbed in something?",
  "What would you like to do again?",
  "What opportunity did you miss today?",
  "How honest were you today?",
  "How kind were you today?",
  "What are three things you're grateful for?",
  "What did you need most today?",
  "What emotion did you feel most often?",
  "Summarize your day in one sentence.",
  "If your day were an animal, what would it be?",
  "Who would you like to share today with?",
  "What comforted you most today?",
  "Did you achieve your goal today?",
  "If you could relive today, what would you change?",
  "What weighed on your mind today?",
  "What words made you smile?",
  "What did you spend the most time on?",
  "If your mood were the sky, what would it look like?",
  "What color represents your day?",
  "When did you feel most courageous?",
  "What positivity did you share with others?",
  "How well did you understand yourself?",
  "What surprised you today?",
  "What role did you play today?",
  "What were you trying to learn?",
  "What did you let go of?",
  "What was the strongest emotion you felt?",
  "When did you wish time would stop?",
  "How different are you from your past self?",
  "If your day were a movie, what would the title be?",
  "What are you most thankful for today?",
  "What fragrance did you leave behind?",
  "What meaningful thing happened to you?",
  "What did you take the lead on?",
  "What made you uncomfortable?",
  "What was your happiest moment?",
  "Who helped you today?",
  "Did you try hard enough today?",
  "How will you feel when you fall asleep tonight?",
  "Describe yourself today in one sentence.",
  "When did you feel most alive?",
  "How relaxed were you today?",
  "How honest were you with yourself?",
  "What words stayed with you the longest?",
  "Did you try something new today?",
  "What color comes to mind when you think of today?",
  "When was the quietest moment of your day?",
  "How do you want to be remembered today?",
  "What small happiness did you miss?",
  "What helped you grow today?",
  "What emotion was the main character today?",
  "Why did you smile?",
  "What's your energy level in percentage?",
  "What were you most focused on?",
  "Who did you think about?",
  "What did you learn today?",
  "When did you feel most like yourself?",
  "Where did you feel most comfortable?",
  "What was your most meaningful conversation?",
  "What moved you today?",
  "What changed in you, even slightly?",
  "What was your posture throughout the day?",
  "Who made you laugh?",
  "What are three things you did well?",
  "What was the most difficult thing?",
  "What didn't you miss?",
  "Who did you want to be with?",
  "What life lesson did you learn?",
  "What made you proud?",
  "If you could restart today, what would you do?",
  "What words are left in your heart?",
  "Did you love yourself today?",
  "What did you think about the most?",
  "Who are you grateful for?",
  "How did you start your day emotionally?",
  "What could you have done better?",
  "Why can you smile when looking back?",
  "What joy did you miss?",
  "What small thing was most meaningful?",
  "What decision do you feel good about?",
  "What relationship did you value?",
  "What made you anxious?",
  "How did you comfort yourself?",
  "What value did you uphold?",
  "What words gave you strength?",
  "Did your expectations come true?",
  "When did you feel least like yourself?",
  "What gave you the biggest realization?",
  "How genuine were you?",
  "What did rest mean to you today?",
  "When were you most immersed?",
  "What relationship brought you comfort?",
  "What did you overlook?",
  "What scene stays in your mind?",
  "What would you like to try again?",
  "When did you feel most accomplished?",
  "How would you organize your emotions?",
  "What gift did you give yourself?",
  "With what mindset did you work?",
  "Who made you smile when you thought of them?",
  "What lingered the most?",
  "What didn't you miss?",
  "What lesson did today give you?",
  "What emotion did you feel most?",
  "What did you give up?",
  "What did you gain?",
  "What made you laugh the most?",
  "What color represents your day?",
  "What season does today feel like?",
  "How well did you take care of your heart?",
  "What are you grateful for?",
  "What change did you dream of?",
  "What emotion did you let go?",
  "What did you promise yourself?",
  "What conversation helped you grow?",
  "What did you learn?",
  "What emotion do you want to fall asleep with?",
  "What did you focus on?",
  "How kind were you to yourself?",
  "What do you regret?",
  "What emotion couldn't you express?",
  "Who are you thankful for?",
  "What shook your heart?",
  "What lesson did you learn today?",
  "What value did you discover?",
  "Who did you help?",
  "How did you start your day?",
  "What choice do you not regret?",
  "What did you concentrate on?",
  "What hope did you hold?",
  "What emotion lasted the longest?",
  "Describe your day in one word.",
  "What moment of gratitude did you miss?",
  "When were you most sincere?",
  "How do you want to end your day emotionally?",
  "What relationship did you invest in?",
  "What emotion hit you hardest?",
  "What moved you most?",
  "What meaning did you find?",
  "What was most special?",
  "What emotion was hardest to handle?",
  "What did you want to postpone?",
  "What brought you the most joy?",
  "Who did you smile at?",
  "What didn't you want to miss?",
  "What made you most proud?",
  "What emotion did you love?",
  "What did you let go of?",
  "What are you grateful for?",
  "What was your biggest realization?",
  "How did you grow as a person?",
  "How did you start your day?",
  "What was meaningful to you?",
  "What dream did you have?",
  "What conversation was most memorable?",
  "What happiness did you feel?",
  "What emotion are you learning?",
  "What did you want to finish?",
  "How do you want to end your day?",
  "What thought stayed with you longest?",
  "What emotion were you most honest about?",
  "What do you want to learn today?",
  "What emotion were you true to?",
  "What relationship are you grateful for?",
  "What small thing made you laugh?",
  "What decision won't you regret?",
  "How did you wake up feeling?",
  "What emotion will you sleep with?",
  "What was your greatest joy?",
  "What emotion do you want to forget?",
  "How did you treat others?",
  "What new emotion did you feel?",
  "What satisfied you?",
  "What's the biggest lesson you learned?",
  "What emotion did you control?",
  "What relationship did you reflect on?",
  "Who are you most grateful for?",
  "What emotion couldn't you let go?",
  "What moment do you want to keep?",
  "What was most meaningful?",
  "How did you start emotionally?",
  "How did you treat yourself?",
  "What words were most memorable?",
  "What emotion did you love?",
  "What hope did you feel?",
  "How did you end emotionally?",
  "What do you want to learn?",
  "What emotion came to mind?",
  "What happiness did you feel?",
  "What emotion were you holding?",
  "What moment are you most grateful for?",
  "How do you want to end your day?",
  "What moved you most?",
  "What new emotion did you discover?",
  "How do you want to fall asleep?",
  "What's the most memorable moment?",
  "Describe your mood in one word.",
  "What made you smile?",
  "What was the hardest moment?",
  "Rate your day out of 10.",
  "Who are you grateful for?",
  "What would you say to yourself?",
  "What did you learn?",
  "When did you make a good choice?",
  "How much did you grow from yesterday?",
  "Are you satisfied with today?",
  "What color are you today?",
  "What made you angry?",
  "When were you most yourself?",
  "When was your most peaceful time?",
  "Do you have any regrets?",
  "What did you focus on?",
  "What small success did you have?",
  "When did you feel most rested?",
  "When did you feel warmth?",
  "How did the weather affect you?",
  "Who did you talk to most?",
  "What made you laugh hardest?",
  "Who did you thank?",
  "What song describes your day?",
  "When were you laziest?",
  "Did you praise yourself?",
  "What thought troubled you?",
  "What photo would capture your day?",
  "Who did you inspire?",
  "What scent describes today?",
  "When were you most focused?",
  "What would you do again?",
  "What opportunity did you miss?",
  "How honest were you?",
  "How kind were you?",
  "Name three things you're grateful for.",
  "What did you need most?",
  "What emotion appeared most often?",
  "Summarize your day in one sentence.",
  "What animal describes your day?",
  "Who would you share today with?",
  "What comforted you most?",
  "Did you reach your goal?",
  "What would you change if you could redo today?",
  "What weighed on your mind?",
  "What words made you smile?",
  "What took up most of your time?",
  "If your mood were the sky, how would it look?",
  "What color is your day?",
  "When were you most brave?",
  "What positivity did you give?",
  "How well did you understand yourself?",
  "What surprised you?",
  "What role did you play?",
  "What were you trying to learn?",
  "What did you let go?",
  "What was your strongest emotion?",
  "When did you want time to stop?",
  "How different are you from before?",
  "What movie title describes today?",
  "What are you most thankful for?",
  "What fragrance did you leave?",
  "What meaningful thing happened?",
  "What did you lead?",
  "What made you uncomfortable?",
  "When were you happiest?",
  "Who helped you?",
  "Did you try enough?",
  "How will you feel falling asleep?",
  "Describe yourself in one sentence.",
  "When did you feel most alive?",
  "How relaxed were you?",
  "How honest were you with yourself?",
  "What words stayed with you?",
  "Did you try something new?",
  "What color comes to mind?",
  "When was the quietest moment?",
  "How do you want to be remembered?",
  "What small happiness did you miss?",
  "What helped you grow?",
  "What emotion led today?",
  "Why did you smile?",
  "What's your energy percentage?",
  "What absorbed you most?",
  "Who did you think of?",
  "What did you learn?",
  "When did you feel most yourself?",
  "Where were you most comfortable?",
  "What was your most meaningful talk?",
  "What touched you?",
  "What changed in you?",
  "What was your attitude throughout?",
  "Who made you laugh?",
  "What three things did you do well?",
  "What was most difficult?",
  "What didn't you miss?",
  "Who did you want to be with?",
  "What life lesson did you learn?",
  "What made you proud?",
  "What would you do differently?",
  "What words remain in your heart?",
  "Did you love yourself?",
  "What did you think about most?",
  "Who are you grateful for?",
  "How did your day start emotionally?",
  "What could you do better?",
  "Why can you smile looking back?",
  "What joy did you miss?",
  "What small thing meant most?",
  "What decision feels right?",
  "What relationship mattered?",
  "What made you anxious?",
  "How did you comfort yourself?",
  "What value did you keep?",
  "What words strengthened you?",
  "Did your hopes come true?",
  "When did you feel unlike yourself?",
  "What realization struck you most?",
  "How sincere were you?",
  "What did rest mean today?",
  "When were you most absorbed?",
  "What relationship comforted you?",
  "What did you overlook?",
  "What scene lingers?",
  "What would you try again?",
  "When did you feel most fulfilled?",
  "How would you sort your emotions?",
  "What gift did you give yourself?",
  "What mindset did you work with?",
  "Who made you smile thinking of them?",
  "What lingered most?",
  "What didn't you miss?",
  "What lesson did today teach?",
  "What emotion dominated?",
  "What did you give up?",
  "What did you gain?",
  "What made you laugh most?"
];

// Get question based on day of year (1-365)
export function getQuestionForDate(dateString) {
  // dateString: YYYY-MM-DD
  const dayOfYearValue = dayjs(dateString).dayOfYear();
  // dayOfYear returns 1-366, we need 0-364 for array index
  const index = (dayOfYearValue - 1) % questions.length;
  return questions[index];
}

// Today's question
export function getTodayQuestion() {
  const today = new Date().toISOString().split('T')[0];
  return {
    question: getQuestionForDate(today),
    date: today
  };
}
