// Question Database
export const questions = [
  "When was your most peaceful moment?",
  "What are you most grateful for today?",
  "When did you last laugh?",
  "What conversation stood out to you?",
  "What did you learn today?",
  "Who do you want to reach out to?",
  "What small win did you have today?",
  "How are you feeling right now?",
  "When were you happiest?",
  "What moved you today?",
  "What beautiful thing did you see today?",
  "What music comes to mind?",
  "What was the best thing you ate?",
  "What scent do you remember?",
  "What was today's highlight?",
  "What would you say to someone?",
  "What are you looking forward to tomorrow?",
  "What do you need most right now?",
  "What were you most focused on today?",
  "What moment do you want to hold onto?",
  "Who do you want to be with?",
  "What color represents today?",
  "When did you feel most comfortable?",
  "What place do you miss?",
  "What emotion did you feel today?",
  "When did you feel warmest?",
  "What gave you comfort?",
  "What choice are you proud of today?",
  "What thought came to mind?",
  "What do you want to do right now?",
  "What was the best part of your day?",
  "Whose voice do you want to hear?",
  "What do you want to remember most?",
  "What small joy did you discover today?",
  "What moment touched your heart?",
  "What made you smile?",
  "What small adventure did you have?",
  "When were you most concentrated?",
  "What fragrance did you enjoy?",
  "What impressive thing did you see?",
  "What are you thankful for?",
  "When were you most joyful?",
  "What surprised you?",
  "What small discovery did you make?",
  "When did you feel most calm?",
  "What taste do you remember?",
  "What warmth did you feel today?",
  "When did you feel best?",
  "What excited you?",
  "What precious moment did you have?",
  "What story do you want to share?",
  "When did you feel most at ease?",
  "What scenery comes to mind?",
  "What did you like today?",
  "What impressed you most?",
  "What made you happy?",
  "What small miracle happened?",
  "When did you feel most relaxed?",
  "What sound did you enjoy?",
  "What satisfied you most today?",
  "Who did you think of?",
  "When did you feel most peaceful?",
  "What moved your heart?",
  "What small happiness did you find?",
  "What was most fun?",
  "What moment was special?",
  "What made you smile today?",
  "What moment was most meaningful?",
  "What touched your soul?",
  "What small pleasure did you have?",
  "When were you most tranquil?",
  "What memory surfaced?",
  "What was the best moment today?",
  "Who are you grateful for?",
  "When did you feel coziest?",
  "What made you laugh?",
  "What small comfort did you receive?",
  "When were you most energetic?",
  "What feeling did you enjoy?",
  "What did you take to heart today?",
  "When did you shine brightest?",
  "What warmed you?",
  "What small peace did you find?",
  "When did you feel most thrilled?",
  "What moment was beautiful?",
  "What made you happy today?",
  "When did you feel most loved?",
  "What brightened your day?",
  "What small wonder did you experience?",
  "When did you feel most alive?",
  "What moment was precious?",
  "What do you want to remember most today?",
  "What time with someone was good?",
  "When were you most excited?",
  "What delighted you?",
  "What small gift did you receive?",
  "When were you most blissful?",
  "What moment was lovely?",
  "What made you smile today?"
];

// Get date-based fixed random question
export function getQuestionForDate(dateString) {
  // dateString: YYYY-MM-DD
  const seed = dateString.split('-').join('');
  const index = parseInt(seed) % questions.length;
  return questions[index];
}

// Today's question
export function getTodayQuestion() {
  const today = new Date().toISOString().split('T')[0];
  return {
    question: getQuestionForDate(today),
    date: today
  };
}
